import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";

const myFont = localFont({
	src: "../fonts/PPPangramSansRounded-Light.otf",
	display: "swap",
	weight: "400",
});

export const metadata: Metadata = {
	title: "YogaHome",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={myFont.className}>
			<body>
				{children}
				<Script
					src="https://identity.netlify.com/v1/netlify-identity-widget.js"
					strategy="afterInteractive"
				/>
				<Script id="netlify-identity-redirect" strategy="afterInteractive">
					{`
            if (window.netlifyIdentity) {
              window.netlifyIdentity.on("init", user => {
                if (!user) {
                  window.netlifyIdentity.on("login", () => {
                    document.location.href = "/admin/";
                  });
                }
              });
            }
          `}
				</Script>
			</body>
		</html>
	);
}
